version: '2'
services:
  go:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "9000:8080" # http
      - "443:443" # https
    # file with environment declarations for the container
    env_file:
      - app.env
    # Link to containers in another service
    links:
      - db
    # sync workspace folder with /go
    volumes:
      - .:/go/app
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mytheresa
      MYSQL_PASSWORD: mytheresa
      MYSQL_ROOT_PASSWORD: mytheresa
      MYSQL_DATABASE: mytheresa
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ./docker/db/data:/var/lib/mysql